### ISSUE TITLE
Car Maintenance Materials disappear when equipped

### ISSUE THREAD

**Issue by Mihosek** [faeldray/DefsLTS#7]
Hello.
I hope this is right place to post a bug.
I noticed when I equip the "Car Maintenance Materials" into hand, it will eventually empty the entire box and change it into plastic box. So then empty container and causing loosing all of it even when is on max condition.
Also tested on original version of Def's mod and it does it there too.

**Comment by faeldray** [comment]
Sorry for the delay in my reply, I wasn't getting notifications for this repo.

I've honestly never used the car stuff from the mod so I'll test it in-game to see what you're referring to.

**Comment by faeldray** [comment]
It seems that the default behavior for drainable items is to start draining once you equip them. Why? I haven't the foggiest. But it was fixed by adding the property `UseWhileEquipped=FALSE`. It also turned out that a lot of other items in this mod didn't have that set either, particularly stack items. It was probably never noticed because no one equipped them before. Anyways, good find, thanks for that!

**Comment by Mihosek** [comment]
Hello.
Thank you for fixing this issue. So I'll download and subscribe again an
updated version on steam as I'm steam user.
